# Generated by Django 5.1.5 on 2025-02-01 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_event_user_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.CharField(default='infinite', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=21, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Meetup', 'Meetup'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
