# Generated by Django 5.1.5 on 2025-02-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_remove_event_capacity_remove_event_event_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.CharField(default='infinite', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='general', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='organizer', max_length=255),
            preserve_default=False,
        ),
    ]
