# Generated by Django 5.1.5 on 2025-02-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_event_capacity_event_event_type_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
