# Generated by Django 5.1.5 on 2025-02-01 10:22

import events_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_set_event_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(default=events_app.models.generate_event_code, editable=False, max_length=20, unique=True),
        ),
    ]
