# Generated by Django 5.1.5 on 2025-02-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0010_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('event_attendance_mode', models.CharField(choices=[('In-Person', 'In-Person'), ('Virtual', 'Virtual')], max_length=10)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('email', 'event')},
            },
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
